### ISSUE TITLE
[Bug] tappable area on hamburger is not right

### ISSUE THREAD

**Issue by hashirshoaeb** [Blocship/star_book#431]
![simulator_screenshot_25141BD3-C026-40B7-B3C3-83D428D93DE3](https://user-images.githubusercontent.com/35165481/222929392-4900356f-ccea-4577-b032-588369d75af1.png)

**Comment by AbdullahAhmedSoomro** [comment]
Removed splash color?

**Comment by hashirshoaeb** [comment]
no, correct the tappable area.

**Comment by Rahul2570089** [comment]
I would like to solve this issue, could you please assign me this issue ?

**Comment by HM-Anwar** [comment]
Check PR #510. Its resolved
