### ISSUE TITLE
Implement list screen

### ISSUE THREAD

**Issue by hashirshoaeb** [Blocship/star_book#459]
![image](https://github.com/hashirshoaeb/star_book/assets/35165481/589da3b4-98cc-4314-93c0-6c7acd08a7aa)

**Comment by hashirshoaeb** [comment]
This screen is not implemented yet. and can be breakdown into multiple issues. 
![Screenshot 2023-10-06 at 10 03 47 AM](https://github.com/Blocship/star_book/assets/35165481/2dd9710b-6eb4-4f0a-b082-fc932b0413ce)
Skip this part while implementing.

**Comment by abdulbari149** [comment]
Hey, I would like to work on it.
