### ISSUE TITLE
Grey screen appearing when clicking on View Details

### ISSUE THREAD

**Issue by hashirshoaeb** [Blocship/star_book#462]
Render issue, when there is not journal.
![image](https://github.com/hashirshoaeb/star_book/assets/35165481/57de84f5-1495-4c32-8ebc-d384d63ee62b)

**Comment by Rahul2570089** [comment]
Hello, I would like to work on this issue, could you please assign it to me ?

**Comment by affanminhas** [comment]
I wanna work in this, please assign it to me
