### ISSUE TITLE
 project Readme.md : Link for "Star Book Board" is not working 

### ISSUE THREAD

**Issue by omerhabib62** [Blocship/star_book#469]
In the screenshot below, the link is pointed is not working for the "Star Book Board".  Just need to update the link for Star Book Board.
![image](https://github.com/Blocship/star_book/assets/38879730/3748f97d-994a-4108-a945-9cf37fe94831)

**Comment by Krishnakalani111** [comment]
could you assign this issue to me?

**Comment by Krishnakalani111** [comment]
I have already opened a PR for the save , could you review it and let me know if any changes are required
