### ISSUE TITLE
Render Issue in settings screen.

### ISSUE THREAD

**Issue by hashirshoaeb** [Blocship/star_book#473]
In debug mode we have long list of tiles. And for small screens it needs to be scrollable.

![simulator_screenshot_271A5299-BD70-41BC-A1D6-3A09EB656758](https://github.com/Blocship/star_book/assets/35165481/607e13ab-684f-4bd4-bf5b-bb0261559657)

**Comment by nafladiva** [comment]
Hello, I would like to work on this if it hasn't been fixed yet

**Comment by CodeWithSuleman** [comment]
Hi, I would like to work on this issue.
