### ISSUE TITLE
Change Documentation in Readme.md 

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#482]
**In Contributing.md**
Replace "To pick something for contribution refer StarBook board. For more, refer CONTRIBUTING.md" with "To pick something for contribution refer CONTRIBUTING.md".

**Comment by omerhabib62** [comment]
Hi! looking forward to work on this.

**Comment by Asfandtariq90** [comment]
Hey, I would love to work on this issue.
