### ISSUE TITLE
Changes Documentation in Contributing.md

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#483]
**In Contributing.md**
replace 'Please checkout the issues and project board' with "Please check out the issues for any current concerns or topics related to the project. Additionally, we now use Discord for project management and communication. Feel free to join our Discord server here for the latest updates and discussions."

**Comment by omerhabib62** [comment]
Hi! looking forward to work on this.

**Comment by Asfandtariq90** [comment]
Hey, I would love to work on this issue.
