### ISSUE TITLE
Help Needed Documentation

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#486]
**In Contributing.md**

_Help Needed Section_

Replace this: https://github.com/hashirshoaeb/star_book/issues with this: https://github.com/Blocship/star_book/issues

**Comment by 123HelloBob** [comment]
Hi! i'd be willing to work on this.

**Comment by omerhabib62** [comment]
Hi! looking forward to work on this.

**Comment by AbdullahAhmedSoomro** [comment]
@omerhabib62 any updates?

**Comment by Redvey** [comment]
@AbdullahAhmedSoomro  I have raise PR about the issue, please do verify

**Comment by AbdullahAhmedSoomro** [comment]
Okay
