### ISSUE TITLE
Change link in Readme.md

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#487]
**In Readme.md**
Replace this: hashirshoaeb/star_book with this: Blocship/star_book

**Comment by Aryashakya** [comment]
Hi, I would like to work on this issue.

**Comment by omerhabib62** [comment]
Hi, I would like to work on this issue.

**Comment by Asfandtariq90** [comment]
Hey, I would love to work on this issue.
