### ISSUE TITLE
[Bug] Intro Screen

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#492]
**Steps to Reproduce**
Just enter your name with spaces like 'Abdullah Ahmed'
It will show you a validation message that `name should only contain alphabetic character`

**Space should be accepted**

So You have to just change Regex:
You can find that text field in IntroScreen [`lib/presentation/screen/intro_screen.dart`].

Also, change the message of validation:
- `name should be less than 15 characters` to `Name should be less than 15 characters`.
- `name should only contain alphabetic characters` to `Use alphabets only, no symbols allowed`.

You can find the validation message in the form_validator file [`li/presentation/shared/form_validator.dart`]
Function Name: `nameValidator`.

![WhatsApp Image 2023-10-07 at 3 26 04 PM](https://github.com/Blocship/star_book/assets/50518325/569e192a-6693-43b3-9b0e-61c2b180d664)

**Comment by CodeWithSuleman** [comment]
Hi, I would like to work on this issue.
