### ISSUE TITLE
Lock Orientation to Portrait

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#496]
- Just Restrict orientation to Portrait

**Comment by CodeWithSuleman** [comment]
Hi, I would like to work on this issue.

**Comment by HM-Anwar** [comment]
@AbdullahAhmedSoomro can you assign this issue?

**Comment by HM-Anwar** [comment]
@AbdullahAhmedSoomro check PR #512 , It's resolved
