### ISSUE TITLE
Create Journal Validation

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#497]
_**Bug**_
No Validation on creating Journals

_**Solution**_
You have to add Validation

_**Hint**_
You can see edit journal screen for understanding, You can find implementation of validation and the message as well.

![WhatsApp Image 2023-10-09 at 10 34 04 AM](https://github.com/Blocship/star_book/assets/50518325/ed751662-2d99-449f-9c81-cd33f05606e0)

**Comment by AlgyJr** [comment]
Hi @AbdullahAhmedSoomro or @hashirshoaeb  can I work on this? it looks stale :)

**Comment by hashirshoaeb** [comment]
Yse sure @AlgyJr

**Comment by HM-Anwar** [comment]
@AbdullahAhmedSoomro Check PR ##514, It's resolved.
