### ISSUE TITLE
[Bug] App Name

### ISSUE THREAD

**Issue by AbdullahAhmedSoomro** [Blocship/star_book#499]
Change name star_book to Starbook
![WhatsApp Image 2023-10-09 at 10 43 44 AM](https://github.com/Blocship/star_book/assets/50518325/b49f0849-b8af-43bb-877b-a324e9bc563b)

**Comment by AryanC19** [comment]
Can you assign this issue to me please?

**Comment by AbdullahAhmedSoomro** [comment]
@HM-Anwar  Any Updates?

**Comment by AryanC19** [comment]
I could do it it one day

**Comment by hashirshoaeb** [comment]
@AryanC19 here you go.

**Comment by HM-Anwar** [comment]
@hashirshoaeb can you assign me this issue?

**Comment by hashirshoaeb** [comment]
Done @HM-Anwar

**Comment by HM-Anwar** [comment]
Check #513, this issue is resolved.
