### ISSUE TITLE
Don't force adding of title and notes

### ISSUE THREAD

**Issue by th8m0z** [Blocship/star_book#528]
**Is your feature request related to a problem? Please describe.**
It's annoying to always have to add title and notes, when I just want to quickly add my mood.

**Describe the solution you'd like**
Make adding title and notes optional.

**Describe alternatives you've considered**
-

I'll get to work on this

**Comment by hashirshoaeb** [comment]
Quick question: how long have you been using Starbook?

**Comment by th8m0z** [comment]
Not very long, I just started trying it out a few weeks ago. But still I think it would make the UX a lot better.

**Comment by hashirshoaeb** [comment]
Makes sense. Go ahead.
