### ISSUE TITLE
Add App Encryption Documentation in info.plist

### ISSUE THREAD

**Issue by hashirshoaeb** [Blocship/star_book#532]
![Screenshot 2024-02-19 at 11 57 48 PM](https://github.com/Blocship/star_book/assets/35165481/b79f3c8b-600d-4695-bcb9-0f03a822cd3e)
https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations

**Comment by LaraKraemer** [comment]
Hi Hashir, I would like to work on this issue. Can you assign me, please? Thank you.
